---
- name: "Set up garage servers"
  hosts: "{{ target if target is defined else 'garage_servers' }}"
  become: true

  roles:
    # This role has no tasks at all
    - role: galaxy/com.devture.ansible.role.playbook_help

    # This role has no tasks at all
    - role: galaxy/com.devture.ansible.role.systemd_docker_base

    - when: devture_timesync_installation_enabled | bool
      role: galaxy/com.devture.ansible.role.timesync
      tags:
        - setup-timesync
        - setup-all
        - install-timesync
        - install-all

    - role: custom/base
      tags:
        - setup-all
        - install-all


    # This role exposes various tags (setup-nextcloud, setup-all, setup-onlyoffice-app, setup-adjust-nextcloud-config, etc.) so we don't tag it here.
    - role: custom/garage

    - when: garage_playbook_traefik_role_enabled | bool
      role: galaxy/com.devture.ansible.role.traefik

    - when: devture_systemd_service_manager_enabled | bool
      role: galaxy/com.devture.ansible.role.systemd_service_manager

    # This is pretty much last, because we want it to better serve as a "last known good configuration".
    # See: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2217#issuecomment-1301487601
    - when: devture_playbook_state_preserver_enabled | bool
      role: galaxy/com.devture.ansible.role.playbook_state_preserver
      tags:
        - setup-all
        - install-all

    - role: galaxy/com.devture.ansible.role.playbook_runtime_messages
