---

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/add_services.yml"
  tags:
    - always


- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - setup-all
    - install-all
