---

- name: Get Garage node prefix
  ansible.builtin.shell:
    cmd:  "docker exec -it garage_{{item.name}} /garage status | awk 'FNR == 3  {print $1}'"
  register: garage_node_prefix
- name: "Print prefix"
  debug:
    msg: "Prefix {{ garage_node_prefix }}"
- name: Get Garage node id
  ansible.builtin.shell:
    cmd: "docker exec -it garage_{{item.name}} /garage node id | awk 'FNR == 1 {print}'"
  register: garage_node_id
- name: "Print id"
  debug:
    msg: "Prefix {{ garage_node_id }}"
- name: Configure Garage nodes
  ansible.builtin.shell:
    cmd: "docker exec --user={{ garage_user_uid }}:{{ garage_user_gid }} garage_{{item.name}} /garage layout assign -z {{ garage_garage_dc }} -c {{ item.capacity }} {{ garage_node_prefix.stdout }}"

