---

- name: Ensure Garage path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
  with_items:
    - {path: "{{ garage_garage_base_path }}", when: true}
    - {path: "{{ garage_garage_config_path }}", when: true}
    - {path: "{{ garage_garage_meta_path }}", when: true}
    - {path: "{{ garage_garage_data_path }}", when: true}

- name: Ensure Garage node data paths exists
  ansible.builtin.file:
    path: "{{ item.data_path }}"
    state: directory
    mode: 0700
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
  loop: "{{ garage_garage_nodes }}"

- name: Ensure Garage node metadata paths exists
  ansible.builtin.file:
    path: "{{ item.metadata_path }}"
    state: directory
    mode: 0700
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
  loop: "{{ garage_garage_nodes }}"


- name: Ensure Garage support files installed
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
    mode: 0640
  with_items:
    - src: "{{ role_path }}/templates/labels.j2"
      dest: "{{ garage_garage_base_path }}/labels"

- name: Ensure garage node configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/garage_node.toml.j2"
    dest: "{{ garage_garage_config_path }}/garage_{{ item.name }}.toml"
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
    mode: 0640
  loop: "{{ garage_garage_nodes }}"

- name: Ensure Garage container image is pulled
  community.docker.docker_image:
    name: "{{ garage_garage_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure garage.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/garage_node.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/garage_{{ item.name }}.service"
    mode: 0644
  loop: "{{ garage_garage_nodes }}"
