# Base directory that contains everything
garage_base_path: "/garage"

garage_user_username: garage
garage_user_uid: 3993
garage_user_gid: 3993

garage_playbook_docker_installation_enabled: true

# The architecture that your server runs.
# Recognized values by us are 'amd64', 'arm32' and 'arm64'.
# Not all architectures support all services, so your experience (on non-amd64) may vary.
garage_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ('arm64' if ansible_architecture == 'aarch64' else ('arm32' if ansible_architecture.startswith('armv') else '')) }}"

garage_docker_network: 'garage'

garage_playbook_traefik_role_enabled: true

garage_garage_debian_buster: false
